console.log("Hello, world!");

const myName = "John Miguel Gawal";
let age = 21;
const number = "09919210545";
const address = "Brgy Manta-angan EB MAGALONA";

console.log(`Name ${myName}`);
console.log(`Age ${age}`);
console.log(`Number ${number}`);
console.log(`Address ${address}`)   

 const heading = document.querySelector("h1");
 console.log (contactHeading);


const projectHeading = document.querySelector("h1");
 console.log (projectHeading);





    




